### ISSUE TITLE
Cannot get this library to build no matter what....I have tried building manually and tried installing via npm 

### ISSUE THREAD

**Issue by sbhatnagar30** [exantech/monero-nodejs-libwallet#12]
I would like to use the sign/verify features of this library, as this is the only javascript library that supports such features for monero. I cannot get this library to install however. Here are relevant output logs:

In file included from /home/bhatnagar/.node-gyp/8.11.3/include/node/node.h:63:0,
                 from ../src/deferredtask.h:3,
                 from ../src/deferredtask.cc:1:
/home/bhatnagar/.node-gyp/8.11.3/include/node/v8.h:3959:39: note: declared here
     V8_WARN_UNUSED_RESULT Maybe<bool> Resolve(Local<Context> context,
                                       ^~~~~~~
../src/deferredtask.cc: In member function ‘void exawallet::DeferredTask::Reject(v8::Isolate*)’:
../src/deferredtask.cc:18:118: warning: ignoring return value of ‘v8::Maybe<bool> v8::Promise::Resolver::Reject(v8::Local<v8::Context>, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
 olate)->Reject(isolate->GetCurrentContext(), v8::String::NewFromUtf8(isolate, errorString.c_str()));
                                                                                                   ^
In file included from /home/bhatnagar/.node-gyp/8.11.3/include/node/node.h:63:0,
                 from ../src/deferredtask.h:3,
                 from ../src/deferredtask.cc:1:
/home/bhatnagar/.node-gyp/8.11.3/include/node/v8.h:3963:39: note: declared here
     V8_WARN_UNUSED_RESULT Maybe<bool> Reject(Local<Context> context,
                                       ^~~~~~
  CXX(target) Release/obj.target/monero/src/wallettasks.o
  CXX(target) Release/obj.target/monero/src/pendingtransaction.o
  SOLINK_MODULE(target) Release/obj.target/monero.node
g++: error: ../deps/libboost_serialization.a: No such file or directory
g++: error: ../deps/libboost_thread.a: No such file or directory
g++: error: ../deps/libboost_system.a: No such file or directory
g++: error: ../deps/libboost_date_time.a: No such file or directory
g++: error: ../deps/libboost_filesystem.a: No such file or directory
g++: error: ../deps/libboost_chrono.a: No such file or directory
g++: error: ../deps/libboost_program_options.a: No such file or directory
g++: error: ../deps/libboost_regex.a: No such file or directory
monero.target.mk:150: recipe for target 'Release/obj.target/monero.node' failed
make: *** [Release/obj.target/monero.node] Error 1
rm binding_gyp_build_monero_target_retrieve_from_github.intermediate
make: Leaving directory '/home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-24-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--module=/home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet/lib/binding/monero.node" "--module_name=monero" "--module_path=/home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet/lib/binding" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --module=/home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet/lib/binding/monero.node --module_name=monero --module_path=/home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet/lib/binding --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.15.0-24-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet/node_modules/.bin/node-pre-gyp" "configure" "build"
node-pre-gyp ERR! cwd /home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet
node-pre-gyp ERR! node -v v8.11.3
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --module=/home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet/lib/binding/monero.node --module_name=monero --module_path=/home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet/lib/binding --napi_version=3 --node_abi_napi=napi' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! monero-nodejs-libwallet@0.2.2 build: `node-pre-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the monero-nodejs-libwallet@0.2.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bhatnagar/.npm/_logs/2018-07-11T20_25_59_390Z-debug.log

Here is the output of the debug log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle monero-nodejs-libwallet@0.2.2~prebuild: monero-nodejs-libwallet@0.2.2
6 info lifecycle monero-nodejs-libwallet@0.2.2~build: monero-nodejs-libwallet@0.2.2
7 verbose lifecycle monero-nodejs-libwallet@0.2.2~build: unsafe-perm in lifecycle true
8 verbose lifecycle monero-nodejs-libwallet@0.2.2~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet/node_modules/.bin:/home/bhatnagar/.nix-profile/bin:/home/bhatnagar/.cargo/bin:/home/bhatnagar/bin:/home/bhatnagar/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle monero-nodejs-libwallet@0.2.2~build: CWD: /home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet
10 silly lifecycle monero-nodejs-libwallet@0.2.2~build: Args: [ '-c', 'node-pre-gyp configure build' ]
11 silly lifecycle monero-nodejs-libwallet@0.2.2~build: Returned: code: 1  signal: null
12 info lifecycle monero-nodejs-libwallet@0.2.2~build: Failed to exec build script
13 verbose stack Error: monero-nodejs-libwallet@0.2.2 build: `node-pre-gyp configure build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid monero-nodejs-libwallet@0.2.2
15 verbose cwd /home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet
16 verbose Linux 4.15.0-24-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error monero-nodejs-libwallet@0.2.2 build: `node-pre-gyp configure build`
22 error Exit status 1
23 error Failed at the monero-nodejs-libwallet@0.2.2 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Any help would be appreciated.

**Comment by naughtyfox** [comment]
Hi! How do you start build?

**Comment by naughtyfox** [comment]
You also may try to install previous version `0.2.1`

**Comment by sbhatnagar30** [comment]
I clone the repo, cd into it and then npm run build. That is how I got the above error messages. 
I will try the previous version.
Thank you for the quick reply.

**Comment by naughtyfox** [comment]
what does `npm install` say?
> I will try the previous version
Nevertheless we'll fix the problem anyway. Sorry for inconvinience.

**Comment by sbhatnagar30** [comment]
I get the same error:

make: Leaving directory '/home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet-e3d03d778d78187a0cb3cb3673fdcbf80470415d/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-24-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--module=/home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet-e3d03d778d78187a0cb3cb3673fdcbf80470415d/lib/binding/monero.node" "--module_name=monero" "--module_path=/home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet-e3d03d778d78187a0cb3cb3673fdcbf80470415d/lib/binding" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet-e3d03d778d78187a0cb3cb3673fdcbf80470415d
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --module=/home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet-e3d03d778d78187a0cb3cb3673fdcbf80470415d/lib/binding/monero.node --module_name=monero --module_path=/home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet-e3d03d778d78187a0cb3cb3673fdcbf80470415d/lib/binding --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet-e3d03d778d78187a0cb3cb3673fdcbf80470415d/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.15.0-24-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet-e3d03d778d78187a0cb3cb3673fdcbf80470415d/node_modules/.bin/node-pre-gyp" "configure" "build"
node-pre-gyp ERR! cwd /home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet-e3d03d778d78187a0cb3cb3673fdcbf80470415d
node-pre-gyp ERR! node -v v8.11.3
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --module=/home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet-e3d03d778d78187a0cb3cb3673fdcbf80470415d/lib/binding/monero.node --module_name=monero --module_path=/home/bhatnagar/Github/Wallet-Investigation/Monero/monero-nodejs-libwallet-e3d03d778d78187a0cb3cb3673fdcbf80470415d/lib/binding --napi_version=3 --node_abi_napi=napi' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! monero-nodejs-libwallet@0.2.1 build: `node-pre-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the monero-nodejs-libwallet@0.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bhatnagar/.npm/_logs/2018-07-11T21_44_26_593Z-debug.log

**Comment by sbhatnagar30** [comment]
I was able to successfully install and use the previous version (0.2.1). Thank you for that. Still do not know why current version is not working.

**Comment by chicoxyzzy** [comment]
@sbhatnagar30 try 0.2.5 please. It should work fine
