### ISSUE TITLE
Wallet synchronise issues

### ISSUE THREAD

**Issue by takaryu** [exantech/monero-nodejs-libwallet#28]
Hi, I have few question wanna ask you:

1. Wallet cant synchronise
I created wallet and open it, it seems like cant synchronise
Already insert wallet.on or wallet.startRefresh function inside
but when I execute js file, it will direct end process and stop the js file
Is like nothing happen

2. Remote node
I tried use as.node.moneroworld.com:18089, but it show disconnected
If use node.moneroworld.com:18089, it is connected
Is that doesn't support or?

3. Blockchain file location
If successful synchronise, blockchain will generate on which folder?

Thanks

**Comment by takaryu** [comment]
Sorry, I had understand what is the issue already
So close this issues, have new question I will ask here again

**Comment by naughtyfox** [comment]
> Blockchain file location
normally it's in `~/.bitmonero/` folder

> If use node.moneroworld.com:18089, it is connected
The synchronization process may take a while. Public nodes often may be outdated which makes it impossible to synchronize with.
